#!/usr/bin/env bash

if [ "$1" == "--version" ]; then
	echo "1.0.0"
	exit 0;
fi

if [ "$1" == "--help" ]; then
	echo "outdated

Options:
	outdated		Open interactive menu updating deps to a \"Wanted\" version
	outdated latest	Open interactive menu updating deps to a \"Latest\" version
	--help			Show this help menu
	--version		Prints version number"
	exit 0;
fi

if [ ! npm -v 2> /dev/null ]; then
	echo "Error: You need a globally installed npm to use this script" >&2
	exit 1
fi

function findipt() {
	if hash ipt 2>/dev/null; then
		# use global ipt install
		echo ipt
	else
		# use npx
		echo "npx ipt"
	fi
}

if [ "$1" == "latest" ]; then
	depwantedversioncutopt=4
else
	depwantedversioncutopt=2
fi

depfinalversiontoinstall="$(npm outdated --parseable | cut -d ':' -f $depwantedversioncutopt | $(findipt))"

if [ -z "$depfinalversiontoinstall" ]; then
	echo "Error: Failed to select a suitable dep to install." >&2
	exit 1
fi

npm install "$depfinalversiontoinstall"
